---
- name: Update path for Go binaries
  lineinfile:
    path: ~/.bashrc
    line: 'export PATH=$PATH:/usr/local/go/bin'
  tags: [golang]

- name: Set GOPATH
  lineinfile:
    path: ~/.bashrc
    line: "export GOPATH=/home/{{ ansible_user_id }}/go"
  tags: [golang]
