---
# https://askubuntu.com/a/1404401/18665
- name: Remove Firefox snap
  snap:
    name: firefox
    state: absent
  become: yes
  when:
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_version is version('22.04', '=')
  tags: [firefox]

# Installing a repo via a PPA (as below) will automatically install the key, but will
# cause a deprecation warning because it gets installed in /etc/apt/trusted.gpg instead of
# /etc/apt/trusted.gpg.d/
- name: Install Mozilla team PPA GPG key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 0AB215679C571D1C8325275B9BDB3D89CE49EC21
    keyring: /etc/apt/trusted.gpg.d/mozillateam.gpg
  become: yes
  when:
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_version is version('22.04', '=')
  tags: [firefox]

- name: Install Mozilla team PPA
  apt_repository:
    repo: ppa:mozillateam/ppa
    update_cache: yes
  become: yes
  when:
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_version is version('22.04', '=')
  tags: [firefox]

- name: Prioritize installation of the apt version of Firefox
  copy:
    src: mozilla-firefox
    dest: /etc/apt/preferences.d/mozilla-firefox
  become: yes
  when:
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_version is version('22.04', '=')
  tags: [firefox]

- name: Configure unattended upgrades to use the apt version of Firefox
  copy:
    content: 'Unattended-Upgrade::Allowed-Origins:: "LP-PPA-mozillateam:${distro_codename}";'
    dest: /etc/apt/apt.conf.d/51unattended-upgrades-firefox
  become: yes
  when:
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_version is version('22.04', '=')
  tags: [firefox]

- name: Install necessary packages
  apt:
    name:
      - firefox
    state: present
  become: yes
  tags: [firefox]

- name: Copy Firefox .desktop file
  copy:
    src: /usr/share/applications/firefox.desktop
    dest: ~/.local/share/applications/firefox.desktop
    force: no
  tags: [firefox]

# The language must be first installed from within the browser preferences in order for this to work
- name: Set Firefox language
  replace:
    path: ~/.local/share/applications/firefox.desktop
    regexp: '^Exec=.*firefox'
    replace: 'Exec=env LC_ALL=fr_CA.utf8 firefox'
    backup: yes
  tags: [firefox]
