---
# This provides Redshift 1.12+, which is needed for time-based transition periods (https://github.com/jonls/redshift/pull/529)
- name: Install Redshift PPA for Ubuntu 16.04 - 18.04
  apt_repository:
    repo: ppa:dobey/redshift-daily
  become: yes
  when:
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_version is version_compare('16.04', '>=')
    - ansible_distribution_version is version_compare('18.04', '<=')
  tags: [redshift]

- name: Install Redshift for Ubuntu >= 16.04
  apt:
    name: redshift-gtk
    state: latest
  become: yes
  when:
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_version is version_compare('16.04', '>=')
  tags: [redshift]

- name: Configure Redshift to autostart
  copy:
    src: /usr/share/applications/redshift-gtk.desktop
    dest: ~/.config/autostart/redshift-gtk.desktop
    force: no
  tags: [redshift]

- name: Copy Redshift configuration
  copy:
    src: redshift.conf
    dest: ~/.config/redshift.conf
  tags: [redshift]
