---
- name: Install Sublime Text GPG key
  apt_key:
    url: https://download.sublimetext.com/sublimehq-pub.gpg
    state: present
  become: yes

- name: Install Sublime Text repository
  apt_repository:
    repo: deb https://download.sublimetext.com/ apt/stable/
    state: present
    filename: sublime-text
  become: yes

- name: Install Sublime Text
  apt:
    name: sublime-text
    state: latest
  become: yes

- name: Set Sublime Text as default editor
  lineinfile:
    path: ~/.bashrc
    regexp: '^export EDITOR=.*'
    line: "export EDITOR='subl -w'"
