---
- name: Install Sublime Text GPG key
  apt_key:
    url: https://download.sublimetext.com/sublimehq-pub.gpg
    state: present
  become: yes
  tags: [sublime-text]

- name: Install Sublime Text repository
  apt_repository:
    repo: deb https://download.sublimetext.com/ apt/stable/
    state: present
    filename: sublime-text
  become: yes
  tags: [sublime-text]

- name: Install Sublime Text
  apt:
    name: sublime-text
    state: present
  become: yes
  tags: [sublime-text]

- name: Set Sublime Text as default editor
  replace:
    path: ~/.bashrc
    regexp: '^export EDITOR=.*'
    replace: export EDITOR='subl -w'
  tags: [sublime-text]
