- name: Install Sublime Text
  # Use dynamic include so skipped tasks won't show in output
  include_tasks: install.yml
  when: (sublime_text_uninstall is not defined) or (sublime_text_uninstall | bool == false)
  tags: [sublime-text]

- name: Uninstall Sublime Text
  # Use dynamic include so skipped tasks won't show in output
  include_tasks: uninstall.yml
  when: (sublime_text_uninstall is defined) and (sublime_text_uninstall | bool == true)
  tags: [sublime-text]
