---
- name: Get Ubuntu release codename
  shell: lsb_release -cs
  changed_when: no
  check_mode: no
  register: release
  tags: [vagrant]

- name: Install Vagrant GPG key
  apt_key:
    url: https://apt.releases.hashicorp.com/gpg
    keyring: /etc/apt/trusted.gpg.d/docker.gpg
  become: yes
  tags: [vagrant]

- name: Install Vagrant repository
  apt_repository:
    repo: deb [arch=amd64] https://apt.releases.hashicorp.com {{ release.stdout }} main
    state: present
    filename: vagrant
    update_cache: yes
  become: yes
  tags: [vagrant]

- name: Install Vagrant
  apt:
    name: vagrant
    state: latest
  become: yes
  tags: [vagrant]

- name: Create cron job to stop running VMs
  cron:
    name: Stop running vagrant VMs
    minute: "15"
    hour: "17"
    # The SSH_AUTH_SOCK stuff is necessary because running vagrant commands requires SSH to connect to the machine,
    # which in turn requires access to the SSH agent. The rest is from https://askubuntu.com/a/746334/18665
    job: "vagrant global-status | awk '/running/{print $1}' | SSH_AUTH_SOCK=/run/user/$(id -u)/keyring/ssh xargs vagrant halt"
  tags: [vagrant]
