---
- name: Get Ubuntu release codename
  shell: lsb_release -cs
  changed_when: no
  check_mode: no
  register: release
  tags: [vagrant]

- name: Install Hashicorp GPG key
  apt_key:
    url: https://apt.releases.hashicorp.com/gpg
    keyring: /etc/apt/trusted.gpg.d/hashicorp.gpg
  become: yes
  tags: [vagrant]

- name: Install Hashicorp repository
  apt_repository:
    repo: deb [arch=amd64] https://apt.releases.hashicorp.com {{ release.stdout }} main
    state: present
    filename: hashicorp
    update_cache: yes
  become: yes
  tags: [vagrant]

# TODO: remove this once it's cleaned up everywhere
- name: Remove /etc/apt/sources.list.d/vagrant.list
  file:
    path: /etc/apt/sources.list.d/vagrant.list
    state: absent
  become: yes
  tags: [vagrant]

- name: Install Vagrant
  apt:
    name: vagrant
    state: latest
  become: yes
  tags: [vagrant]

- name: Create cron job to stop running VMs
  cron:
    name: Stop running vagrant VMs
    minute: '15'
    hour: '17'
    # The SSH_AUTH_SOCK stuff is necessary because running vagrant commands requires SSH to connect to the machine,
    # which in turn requires access to the SSH agent. The rest is from https://askubuntu.com/a/746334/18665
    job: "vagrant global-status | awk '/running/{print $1}' | SSH_AUTH_SOCK=/run/user/$(id -u)/keyring/ssh xargs vagrant halt"
    # This is only added if the machine is a desktop 🤓
    state: "{{ 'present' if linux_machine_type == 'desktop' else 'absent' }}"
  tags: [vagrant]
