---
- name: Install VS Code GPG key
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present
  become: yes

- name: Install VS Code repository
  apt_repository:
    repo: deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main
    state: present
    filename: vscode
  become: yes

- name: Install VS Code
  apt:
    name: code
    state: present
  become: yes
