---
- block:
    - name: Install VS Code repository
      apt_repository:
        repo: deb [arch=amd64] http://packages.microsoft.com/repos/vscode stable main
        state: present
        filename: vscode
      become: yes
      tags: [vscode]

  rescue:
    - name: Install VS Code GPG key
      apt_key:
        url: https://packages.microsoft.com/keys/microsoft.asc
        state: present
      become: yes
      tags: [vscode]

    - name: Install VS Code repository
      apt_repository:
        repo: deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main
        state: present
        filename: vscode
      become: yes
      tags: [vscode]

- name: Install VS Code
  apt:
    name: code
    state: present
  become: yes
  tags: [vscode]

- name: Install extensions
  shell: code --list-extensions | grep '{{ item }}' || code --install-extension '{{ item }}' > /dev/null
  with_items:
    - bmaupin.theme-solarized-dark-high-contrast
    - shardulm94.trailing-spaces
  register: result
  changed_when: result.stdout.find(item) == -1
  tags: [vscode]

- name: Copy User/keybindings.json
  copy:
    src: keybindings.json
    dest: ~/.config/Code/User/keybindings.json
  tags: [vscode]

- name: Copy User/settings.json
  copy:
    src: settings.json
    dest: ~/.config/Code/User/settings.json
  tags: [vscode]

- name: Set VS Code as default editor
  lineinfile:
    path: ~/.bashrc
    regexp: '^export EDITOR=.*'
    line: "export EDITOR='code -w -n'"
  tags: [vscode]
