---
# NOTE: The key (this task) and repository (next task) files are both managed by vscode.
#       If they changing, we should manage them differently, for example:
#       - Only run this task if vscode isn't installed, just for initial setup
#       - Or create the files manually and never update them
- name: Install Microsoft GPG key
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    keyring: /usr/share/keyrings/microsoft.gpg
  become: yes
  tags: [vscode]

- name: Install VS Code repository
  deb822_repository:
    name: vscode
    types: deb
    uris: https://packages.microsoft.com/repos/code
    suites: stable
    components:
      - main
    architectures:
      - amd64
      - arm64
      - armhf
    signed_by: /usr/share/keyrings/microsoft.gpg
  become: yes
  tags: [vscode]

- name: Remove old repository entries
  apt_repository:
    repo: '{{ item }}'
    state: absent
    filename: vscode
  with_items:
    - 'deb [arch=amd64,arm64,armhf] http://packages.microsoft.com/repos/code stable main'
  become: yes
  tags: [vscode]

- name: Install VS Code
  apt:
    name: code
    state: latest
  become: yes
  tags: [vscode]

- name: Install extensions
  shell: code --list-extensions | grep '{{ item }}' || code --install-extension '{{ item }}' > /dev/null
  with_items:
    - bmaupin.theme-solarized-dark-high-contrast
    - dbaeumer.vscode-eslint
    - esbenp.prettier-vscode
    - shardulm94.trailing-spaces
  register: result
  changed_when: result.stdout.find(item) == -1
  tags: [vscode]

- name: Copy User/keybindings.json
  copy:
    src: keybindings.json
    dest: ~/.config/Code/User/keybindings.json
  tags: [vscode]

- name: Copy User/settings.json
  copy:
    src: settings.json
    dest: ~/.config/Code/User/settings.json
  tags: [vscode]

# NOTE: Only use this when `"window.restoreWindows": "preserve",` is also set in
#       settings.json, otherwise previously opened windows and any unsaved content may be
#       lost.
- name: Set VS Code as default editor
  lineinfile:
    path: ~/.bashrc
    regexp: '^export EDITOR=.*'
    line: "export EDITOR='code -w -n'"
  tags: [vscode]

# This should be set up by the code package but every once in a while it seems to be missing
- name: Set up /usr/bin/code symlink
  file:
    src: /usr/share/code/bin/code
    dest: /usr/bin/code
    state: link
  become: yes
  tags: [vscode]

# https://code.visualstudio.com/docs/setup/linux#_visual-studio-code-is-unable-to-watch-for-file-changes-in-this-large-workspace-error-enospc
- name: Increase inotify watches
  lineinfile:
    path: /etc/sysctl.conf
    regexp: '^fs.inotify.max_user_watches=.*'
    line: fs.inotify.max_user_watches=524288
  become: yes
  tags: [vscode]
