---
- block:
    - name: Install VS Code repository
      apt_repository:
        repo: deb [arch=amd64] {{ vscode_repository_url }} stable main
        state: present
        filename: vscode
        update_cache: yes
      become: yes
      tags: [vscode]

  rescue:
    - name: Install VS Code GPG key
      apt_key:
        url: https://packages.microsoft.com/keys/microsoft.asc
        state: present
      become: yes
      tags: [vscode]

    - name: Install VS Code repository
      apt_repository:
        repo: deb [arch=amd64] {{ vscode_repository_url }} stable main
        state: present
        filename: vscode
        update_cache: yes
      become: yes
      tags: [vscode]

- name: Install VS Code
  apt:
    name: code
    state: latest
  become: yes
  tags: [vscode]

- name: Install extensions
  shell: code --list-extensions | grep '{{ item }}' || code --install-extension '{{ item }}' > /dev/null
  with_items:
    - bmaupin.copy-without-formatting
    - bmaupin.theme-solarized-dark-high-contrast
    - dbaeumer.vscode-eslint
    - shardulm94.trailing-spaces
  register: result
  changed_when: result.stdout.find(item) == -1
  tags: [vscode]

- name: Copy User/keybindings.json
  copy:
    src: keybindings.json
    dest: ~/.config/Code/User/keybindings.json
  tags: [vscode]

- name: Copy User/settings.json
  copy:
    src: settings.json
    dest: ~/.config/Code/User/settings.json
  tags: [vscode]

- name: Set VS Code as default editor
  lineinfile:
    path: ~/.bashrc
    regexp: '^export EDITOR=.*'
    line: "export EDITOR='code -w -n'"
  tags: [vscode]

# This should be set up by the code package but every once in a while it seems to be missing
- name: Set up /usr/bin/code symlink
  file:
    src: /usr/share/code/bin/code
    dest: /usr/bin/code
    state: link
  become: yes
  tags: [vscode]
