---
- name: Check if VS Code is installed
  shell: dpkg -l code
  changed_when: no
  check_mode: no
  failed_when: no
  register: result
  tags: [vscode, vscode-install]

- name: Include VS Code install tasks
  # Use dynamic include so skipped tasks won't show in output
  include_tasks: install.yml
  when: result.rc is defined and result.rc != 0
  tags: [vscode, vscode-install]

- name: Install extensions
  shell: code --list-extensions | grep '{{ item }}' || code --install-extension '{{ item }}' > /dev/null
  with_items:
    - bmaupin.theme-solarized-dark-high-contrast
    - shardulm94.trailing-spaces
  register: result
  changed_when: result.stdout.find(item) == -1
  tags: [vscode]

- name: Copy User/keybindings.json
  copy:
    src: keybindings.json
    dest: ~/.config/Code/User/keybindings.json
  tags: [vscode]

- name: Copy User/settings.json
  copy:
    src: settings.json
    dest: ~/.config/Code/User/settings.json
  tags: [vscode]

- name: Set VS Code as default editor
  replace:
    path: ~/.bashrc
    regexp: '^export EDITOR=.*'
    replace: "export EDITOR='code -w -n'"
  tags: [vscode]
