---
- name: Make sure driver for Broadcom BCM43228 is installed
  apt:
    name: bcmwl-kernel-source
    state: present
  become: yes
  tags: [home-laptop]

- name: Remove undesired packages
  apt:
    name:
      - mlocate
    state: absent
    purge: yes
  become: yes
  tags: [home-laptop]

- name: Handle brightness keys with Xfce Power Manager
  shell: >
    xfconf-query -c xfce4-power-manager -p '{{ item.property }}' | grep '{{ item.value }}' ||
    xfconf-query -c xfce4-power-manager -p '{{ item.property }}' -t '{{ item.type }}' -n -s '{{ item.value }}'
  with_items:
    - { property: "/xfce4-power-manager/brightness-switch", type: int, value: "0" }
    - { property: "/xfce4-power-manager/handle-brightness-keys", type: bool, value: "true" }
  register: result
  changed_when: result.stdout.find(item.value) == -1
  when:
    - "'ubuntu-xfce' in ansible_role_names"
    - ansible_distribution == "Ubuntu" and ansible_distribution_version != "16.04"
  tags: [home-laptop]

# For some reason the brightness increments when using Xfce Power Manager are way too big
- name: Don't handle brightness keys with Xfce Power Manager
  shell: >
    xfconf-query -c xfce4-power-manager -p '{{ item.property }}' | grep '{{ item.value }}' ||
    xfconf-query -c xfce4-power-manager -p '{{ item.property }}' -t '{{ item.type }}' -n -s '{{ item.value }}'
  with_items:
    - { property: "/xfce4-power-manager/brightness-switch", type: int, value: "1" }
    - { property: "/xfce4-power-manager/handle-brightness-keys", type: bool, value: "false" }
  register: result
  changed_when: result.stdout.find(item.value) == -1
  when:
    - "'ubuntu-xfce' in ansible_role_names"
    - ansible_distribution == "Ubuntu" and ansible_distribution_version == "16.04"
  tags: [home-laptop]

- name: Disable bluetooth auto power on (Gnome)
  lineinfile:
    path: ~/.profile
    line: "rfkill block bluetooth"
  when: "'ubuntu-gnome' in ansible_role_names"
  tags: [home-laptop]

- name: Disable bluetooth auto power on (Xfce)
  lineinfile:
    key: "/org/blueman/plugins/powermanager/auto-power-on"
    value: "false"
  when: "'ubuntu-xfce' in ansible_role_names"
  tags: [home-laptop]

- name: Disable Gnome Tracker indexing
  dconf:
    key: "{{ item.key }}"
    value: "{{ item.value | string }}"
  loop:
    - { key: /org/freedesktop/Tracker/Miner/Files/crawling-interval, value: "-2" }
    - { key: /org/freedesktop/Tracker/Miner/Files/enable-monitors, value: "false" }
  tags: [home-laptop]

# TODO: This may have been fixed starting with kernel 5.7;
# #f that's the case we may be able to remove this once the 5.7 kernel comes to Ubuntu 20.04 HWE
# https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1808418
- name: Work around boot errors
  replace:
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX=.*'
    replace: 'GRUB_CMDLINE_LINUX="intremap=off"'
  become: yes
  notify: Update grub
  tags: [home-laptop]
