---
- name: Disable daily mlocate update
  file:
    dest: /etc/cron.daily/mlocate
    mode: "a-x"
  become: yes

- name: Set permissions for hddtemp
  file:
    dest: /usr/sbin/hddtemp
    mode: "u+s"
  become: yes

- name: Handle brightness keys with Xfce Power Manager
  shell: >
    xfconf-query -c xfce4-power-manager -p '{{ item.property }}' | grep '{{ item.value }}' ||
    xfconf-query -c xfce4-power-manager -p '{{ item.property }}' -t '{{ item.type }}' -n -s '{{ item.value }}'
  with_items:
    - { property: "/xfce4-power-manager/brightness-switch", type: int, value: "0" }
    - { property: "/xfce4-power-manager/handle-brightness-keys", type: bool, value: "true" }
  register: result
  changed_when: result.stdout.find(item.value) == -1
  when:
    - ansible_distribution == "Ubuntu" and ansible_distribution_version != "16.04"

# For some reason the brightness increments when using Xfce Power Manager are way too big
- name: Don't handle brightness keys with Xfce Power Manager
  shell: >
    xfconf-query -c xfce4-power-manager -p '{{ item.property }}' | grep '{{ item.value }}' ||
    xfconf-query -c xfce4-power-manager -p '{{ item.property }}' -t '{{ item.type }}' -n -s '{{ item.value }}'
  with_items:
    - { property: "/xfce4-power-manager/brightness-switch", type: int, value: "1" }
    - { property: "/xfce4-power-manager/handle-brightness-keys", type: bool, value: "false" }
  register: result
  changed_when: result.stdout.find(item.value) == -1
  when:
    - ansible_distribution == "Ubuntu" and ansible_distribution_version == "16.04"

- name: Disable bluetooth auto power on
  dconf:
    key: "/org/blueman/plugins/powermanager/auto-power-on"
    value: "false"

# https://forums.lenovo.com/t5/Linux-Discussion/T430u-Linux-doesn-t-boot-without-acpi-off/m-p/4237857/highlight/true#M11839
# https://web.archive.org/web/20180919160303/https://evilazrael.de/content/getting-linux-boot-lenovo-thinkpad-e485e585
- name: Work around APIC errors
  replace:
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX_DEFAULT=.*'
    replace: 'GRUB_CMDLINE_LINUX_DEFAULT="quiet splash noapic"'
  become: yes
  notify: Update grub

- name: Disable Docker service
  service:
    name: docker.service
    enabled: no
  become: yes

- name: Disable Docker socket
  service:
    name: docker.socket
    enabled: no
  become: yes
