---
- name: Update initramfs
  command: update-initramfs -u -k all
  become: yes

- name: Restart pulseaudio
  service:
    name: pulseaudio
    state: restarted
    scope: user
  when:
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_version is version('22.04', '=')
