---
- name: Update initramfs
  command: update-initramfs -u -k all
  become: yes

- name: Restart pulseaudio
  service:
    name: pulseaudio
    state: restarted
    scope: user

# TODO: Remove this when the corresponding task is removed
- name: Enable disable-gnome-extensions
  systemd:
    name: disable-gnome-extensions.service
    daemon_reload: true
    enabled: yes
    scope: user
