---
- name: Configure cups server
  lineinfile:
    path: /etc/cups/cups-browsed.conf
    line: BrowsePoll {{ cups_server }}
  become: yes
  notify: Restart cups-browsed
  tags: [office]

- name: Configure cups user
  lineinfile:
    path: ~/.profile
    line: export CUPS_USER={{ cups_user }}
  tags: [office]

# This actually needs to be set from within the application (3 dots menu > Settings > Auto-start application) but we'll
# leave it here as a reminder
- name: Automatically start Teams on login
  copy:
    src: /usr/share/applications/teams.desktop
    dest: ~/.config/autostart/teams.desktop
    # Don't overwrite the file; the one Teams copies via the UI may be different
    force: no
  when:
    - "'teams' in ansible_role_names"
  tags: [office]
