---
- name: Configure cups server
  lineinfile:
    path: /etc/cups/cups-browsed.conf
    line: BrowsePoll {{ cups_server }}
  become: true
  notify: Restart cups-browsed
  tags: [office]

- name: Configure cups user
  lineinfile:
    path: ~/.profile
    line: export CUPS_USER={{ cups_user }}
  tags: [office]

- name: Block domains
  blockinfile:
    path: /etc/hosts
    marker: '# {mark} ANSIBLE MANAGED BLOCK - Block domains'
    block: |
      0.0.0.0 www.dailymotion.com
      # Spotify
      # 0.0.0.0 daily-mix.scdn.co
      0.0.0.0 dailymix-images.scdn.co
      0.0.0.0 i.scdn.co
      0.0.0.0 i2o.scdn.co
      0.0.0.0 image-cdn-ak.spotifycdn.com
      0.0.0.0 mosaic.scdn.co
      0.0.0.0 newjams-images.scdn.co
      0.0.0.0 pl.scdn.co
      0.0.0.0 seed-mix-image.spotifycdn.com
      0.0.0.0 seeded-session-images.scdn.co
      0.0.0.0 t.scdn.co
      0.0.0.0 thisis-images.scdn.co
      0.0.0.0 thisis-images.spotifycdn.com
  become: true
  tags: [office]

- name: Install CA certificates
  ansible.builtin.copy:
    dest: '/usr/local/share/ca-certificates/{{ item.filename }}'
    content: '{{ item.content }}'
    owner: root
    group: root
    mode: '0644'
  loop: '{{ office_ca_certificates }}'
  become: true
  notify: Update CA certificates
  tags: [office]

- name: Create policies.json for Firefox
  ansible.builtin.template:
    dest: /usr/lib/firefox/distribution/policies.json
    src: policies.json.j2
    owner: root
    group: root
    mode: '0644'
  become: true
  tags: [office]
