---
- name: Configure firewall
  include: ufw.yml

- name: Run tasks for Ubuntu <= 14.04
  include: ubuntu-le-1404.yml
  when:
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_version | version_compare('14.04', '<=')

- name: Run tasks for Ubuntu >= 16.04
  include: ubuntu-ge-1604.yml
  when:
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_version | version_compare('16.04', '>=')

- name: Remove undesired packages
  apt:
    name: "{{ item }}"
    state: absent
    purge: yes
  with_items:
    - empathy
    - evolution
  become: yes

- name: Install desired packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - apt-file
    - deja-dup
    - indicator-multiload
    - language-pack-fr
    - libreoffice-calc
    - libreoffice-impress
    - libreoffice-writer
    - mpv
    - nmap
    - pidgin
    - pidgin-sipe
    - python3
    - remmina
    - shotwell
    - vim
    - vlc
  become: yes

- name: Install LibreOffice French support
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - hyphen-fr
    - libreoffice-l10n-fr
    - myspell-fr
    - mythes-fr
  become: yes

- name: Install Google Chrome
  apt:
    deb: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  become: yes

- name: Copy Chrome .desktop file
  copy:
    src: /usr/share/applications/google-chrome.desktop
    dest: ~/.local/share/applications/google-chrome.desktop
    force: no

- name: Set Chrome language
  replace:
    path: ~/.local/share/applications/google-chrome.desktop
    regexp: '^Exec=/usr/bin/google-chrome-stable'
    replace: 'Exec=env LANGUAGE=fr /usr/bin/google-chrome-stable'
    backup: yes

- name: Copy .gitconfig
  copy:
    src: .gitconfig
    dest: ~/.gitconfig
    backup: yes

- name: Copy .vimrc
  copy:
    src: .vimrc
    dest: ~/.vimrc
    backup: yes

- name: Create ~/.fonts directory
  file:
    path: ~/.fonts
    state: directory

# This is for Office 365/Word Online (https://askubuntu.com/a/983192/18665)
- name: Install Symbol font
  get_url:
    url: https://source.winehq.org/git/wine.git/blob/HEAD:/fonts/symbol.ttf
    dest: ~/.fonts/symbol.ttf
  notify: Rebuild font cache

# This is for Office 365/Word Online (https://askubuntu.com/a/983192/18665)
- name: Install Wingdings font
  get_url:
    url: https://source.winehq.org/git/wine.git/blob/HEAD:/fonts/wingding.ttf
    dest: ~/.fonts/wingding.ttf
  notify: Rebuild font cache

- name: Default to Python 3 for future-proofing
  lineinfile:
    path: ~/.bashrc
    line: 'alias python=python3'

# Used for synaptic quick search function:
# http://reformedmusings.wordpress.com/2009/06/05/fixing-update-apt-xapian-in-ubuntu-9-04-jaunty/
- name: Disable apt-xapian-index
  file:
    path: /etc/cron.weekly/apt-xapian-index
    mode: "a-x"
  become: yes

- name: Remove grub recovery menu entry
  replace:
    path: /etc/default/grub
    regexp: '^#GRUB_DISABLE_RECOVERY="true"$'
    replace: 'GRUB_DISABLE_RECOVERY="true"'
    backup: yes
  become: yes
  notify: Update grub

- name: Remove grub memory test menu entry
  file:
    path: /etc/grub.d/20_memtest86+
    mode: "a-x"
  become: yes
  notify: Update grub

- name: Apt autoremove
  apt:
    autoremove: yes
  become: yes
  register: result
  changed_when: result.stdout.find('0 to remove') == -1

# Ansible has a dconf module but it doesn't work in Ubuntu 14.04 because python-psutil is < 4.0
- name: Configure frequency of full Deja Dup backups
  shell: >
    dconf read /org/gnome/deja-dup/full-backup-period | grep 180 ||
    dconf write /org/gnome/deja-dup/full-backup-period 180
  register: result
  changed_when: result.stdout.find('180') == -1

# Configure length of time to keep backups for since there's currently no way to limit by size
# (https://bugs.launchpad.net/deja-dup/+bug/846852)
- name: Configure length of time to keep Deja Dup backups
  shell: >
    dconf read /org/gnome/deja-dup/delete-after | grep 730 ||
    dconf write /org/gnome/deja-dup/delete-after 730
  register: result
  changed_when: result.stdout.find('730') == -1

- name: Update apt-file cache
  command: apt-file update
  become: yes
