---
- name: Do encrypted tasks
  include: vault.yml
  tags: [ubuntu-common]

- name: Configure firewall
  include: ufw.yml
  tags: [ubuntu-common]

- name: Remove undesired packages
  apt:
    name:
      - apt-xapian-index
      - empathy
      - evolution
    state: absent
    purge: yes
  become: yes
  tags: [ubuntu-common]

- name: Install desired packages
  apt:
    name:
      - mpv
      - vim
    state: present
  become: yes
  tags: [ubuntu-common]

- name: Disable annoying System program problem detected popup
  replace:
    path: /etc/default/apport
    regexp: '^enabled=.*'
    replace: 'enabled=0'
  become: yes
  tags: [ubuntu-common]

- name: Copy .vimrc
  copy:
    src: .vimrc
    dest: ~/.vimrc
    backup: yes
  tags: [ubuntu-common]

# https://unix.stackexchange.com/a/19320/14436
- name: Enable colour support in less by default
  lineinfile:
    path: ~/.bashrc
    line: 'alias less="less -R"'
  tags: [ubuntu-common]

- name: Default to Python 3 for future-proofing
  lineinfile:
    path: ~/.bashrc
    line: 'alias python=python3'
  tags: [ubuntu-common]

- name: Remove grub recovery menu entry
  replace:
    path: /etc/default/grub
    regexp: '^#GRUB_DISABLE_RECOVERY="true"$'
    replace: 'GRUB_DISABLE_RECOVERY="true"'
    backup: yes
  become: yes
  notify: Update grub
  tags: [ubuntu-common]

- name: Remove grub memory test menu entry
  file:
    path: /etc/grub.d/20_memtest86+
    mode: 'a-x'
  become: yes
  notify: Update grub
  tags: [ubuntu-common]

# This allows us to run newer kernels on LTS versions of Ubuntu
# https://wiki.ubuntu.com/Kernel/LTSEnablementStack
- name: Install the HWE kernel
  apt:
    name: linux-generic-hwe-20.04
    install_recommends: yes
  become: yes
  when:
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_version is version('20.04', '=')
  tags: [ubuntu-common]

# Ideally this should run after all other apt tasks in this role
- name: Apt autoremove
  apt:
    autoremove: yes
    purge: yes
  become: yes
  register: result
  changed_when: result.stdout.find(' 0 to remove') == -1
  tags: [ubuntu-common]

- name: Copy .eslintrc
  copy:
    src: .eslintrc
    dest: ~/.eslintrc
    backup: yes
  tags: [ubuntu-common]

# Defaults to 4 GB or 10% of disk space
# https://www.freedesktop.org/software/systemd/man/journald.conf.html#SystemMaxUse=
# To see used space: journalctl --disk-usage
- name: Limit size of systemd journal
  replace:
    path: /etc/systemd/journald.conf
    regexp: '^(#)?SystemMaxUse=.*'
    replace: 'SystemMaxUse=1G'
  become: yes
  tags: [ubuntu-common]

- name: Block domains
  blockinfile:
    path: /etc/hosts
    block: |
      0.0.0.0 www.dailymotion.com
  become: yes
  tags: [ubuntu-common]
