---
- name: Include workaround tasks
  import_tasks: workarounds.yml

- name: Do encrypted tasks
  include: vault.yml

- name: Configure firewall
  include: ufw.yml

- name: Run tasks for Ubuntu <= 14.04
  include: ubuntu-le-1404.yml
  when:
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_version is version_compare('14.04', '<=')

- name: Remove undesired packages
  apt:
    name:
      - apt-xapian-index
      - empathy
      - evolution
    state: absent
    purge: yes
  become: yes

- name: Install desired packages
  apt:
    name:
      - apt-file
      - indicator-multiload
      - language-pack-fr
      - libreoffice-calc
      - libreoffice-impress
      - libreoffice-writer
      - mpv
      - pidgin
      - pidgin-sipe
      # Required for Ansible dconf module
      - python-psutil
      - python3
      - remmina
      - shotwell
      - vim
    state: present
  become: yes

- name: Install LibreOffice French support
  apt:
    name:
      - hyphen-fr
      - libreoffice-l10n-fr
      - myspell-fr
      - mythes-fr
    state: present
  become: yes

- name: Copy .vimrc
  copy:
    src: .vimrc
    dest: ~/.vimrc
    backup: yes

- name: Create ~/.fonts directory
  file:
    path: ~/.fonts
    state: directory

# This is for Office 365/Word Online (https://askubuntu.com/a/983192/18665)
- name: Install Symbol font
  get_url:
    url: https://source.winehq.org/git/wine.git/blob/HEAD:/fonts/symbol.ttf
    dest: ~/.fonts/symbol.ttf
  notify: Rebuild font cache

# This is for Office 365/Word Online (https://askubuntu.com/a/983192/18665)
- name: Install Wingdings font
  get_url:
    url: https://source.winehq.org/git/wine.git/blob/HEAD:/fonts/wingding.ttf
    dest: ~/.fonts/wingding.ttf
  notify: Rebuild font cache

- name: Default to Python 3 for future-proofing
  lineinfile:
    path: ~/.bashrc
    line: 'alias python=python3'

- name: Remove grub recovery menu entry
  replace:
    path: /etc/default/grub
    regexp: '^#GRUB_DISABLE_RECOVERY="true"$'
    replace: 'GRUB_DISABLE_RECOVERY="true"'
    backup: yes
  become: yes
  notify: Update grub

- name: Remove grub memory test menu entry
  file:
    path: /etc/grub.d/20_memtest86+
    mode: "a-x"
  become: yes
  notify: Update grub

- name: Apt autoremove
  apt:
    autoremove: yes
  become: yes
  register: result
  changed_when: result.stdout.find(' 0 to remove') == -1

- name: Configure indicator-multiload
  shell: >
    dconf read '{{ item.property }}' | grep '{{ item.value }}' ||
    dconf write '{{ item.property }}' '{{ item.value }}'
  with_items:
    - { property: "/de/mh21/indicator-multiload/general/autostart", value: "true" }
    - { property: "/de/mh21/indicator-multiload/graphs/load/enabled", value: "true" }
    - { property: "/de/mh21/indicator-multiload/graphs/cpu/enabled", value: "true" }
    - { property: "/de/mh21/indicator-multiload/graphs/disk/enabled", value: "true" }
    - { property: "/de/mh21/indicator-multiload/graphs/net/enabled", value: "true" }
    - { property: "/de/mh21/indicator-multiload/graphs/swap/enabled", value: "true" }
    - { property: "/de/mh21/indicator-multiload/graphs/mem/enabled", value: "true" }
  register: result
  changed_when: result.stdout.find(item.value) == -1

- name: Copy .eslintrc
  copy:
    src: .eslintrc
    dest: ~/.eslintrc
    backup: yes
