---
- name: Include workaround tasks
  import_tasks: workarounds.yml

- name: Do encrypted tasks
  include: vault.yml

- name: Configure firewall
  include: ufw.yml

- name: Remove undesired packages
  apt:
    name:
      - apt-xapian-index
      - empathy
      - evolution
    state: absent
    purge: yes
  become: yes

- name: Install desired packages
  apt:
    name:
      - mpv
      - python3
      - vim
    state: present
  become: yes

- name: Disable annoying System program problem detected popup
  replace:
    path: /etc/default/apport
    regexp: '^enabled=.*'
    replace: 'enabled=0'
  become: yes

- name: Copy .vimrc
  copy:
    src: .vimrc
    dest: ~/.vimrc
    backup: yes

- name: Default to Python 3 for future-proofing
  lineinfile:
    path: ~/.bashrc
    line: 'alias python=python3'

- name: Remove grub recovery menu entry
  replace:
    path: /etc/default/grub
    regexp: '^#GRUB_DISABLE_RECOVERY="true"$'
    replace: 'GRUB_DISABLE_RECOVERY="true"'
    backup: yes
  become: yes
  notify: Update grub

- name: Remove grub memory test menu entry
  file:
    path: /etc/grub.d/20_memtest86+
    mode: "a-x"
  become: yes
  notify: Update grub

- name: Apt autoremove
  apt:
    autoremove: yes
  become: yes
  register: result
  changed_when: result.stdout.find(' 0 to remove') == -1

- name: Copy .eslintrc
  copy:
    src: .eslintrc
    dest: ~/.eslintrc
    backup: yes
