---
- name: Install packages for Ubuntu <= 14.04
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    # Provides purge-old-kernels, used by Remove old kernels
    - bikeshed
    - icedtea-7-plugin
    - openjdk-7-jdk
  become: yes

- name: Remove old kernels
  command: purge-old-kernels -y
  become: yes
  register: result
  changed_when: result.stdout.find('No kernels are eligible for removal') == -1
