---
# https://bugs.launchpad.net/ubuntu/+source/console-setup/+bug/1612951
- name: Work around bug with /etc/default/keyboard
  lineinfile:
    path: ~/.xprofile
    line: 'setxkbmap -option compose:ralt'
    create: yes
  when: ansible_distribution == "Ubuntu" and ansible_distribution_version == "16.04"

# https://bugs.launchpad.net/ubuntu/+source/shimmer-themes/+bug/881472
- name: Fix missing scrollbar arrow buttons with greybird theme
  replace:
    path: /usr/share/themes/Greybird/gtk-3.0/gtk-widgets.css
    regexp: '^(\s+-GtkScrollbar.+has.+stepper)'
    replace: '#\1'
    backup: yes
  become: yes
  when: ansible_distribution == "Ubuntu" and ansible_distribution_version == "16.04"

- name: Check what version of Whisker Menu is installed
  shell: dpkg-query --showformat='${Version}' --show xfce4-whiskermenu-plugin
  changed_when: no
  check_mode: no
  failed_when: no
  register: result
  when: ansible_distribution == "Ubuntu" and ansible_distribution_version == "14.04"

# 14.04 comes with Whisker Menu which is often very slow to show the list of applications
- name: Install Whisker Menu 1.4
  apt:
    deb: http://mirrors.kernel.org/ubuntu/pool/universe/x/xfce4-whiskermenu-plugin/xfce4-whiskermenu-plugin_1.4.0-1ubuntu1~ubuntu14.04.1_amd64.deb
  become: yes
  when: ansible_distribution == "Ubuntu" and ansible_distribution_version == "14.04" and result.stdout is defined and result.stdout | version_compare('1.4', '<')

# https://bugs.launchpad.net/ubuntu/+source/shimmer-themes/+bug/881472
- name: Fix missing scrollbar arrow buttons with greybird theme
  replace:
    path: /usr/share/themes/Greybird/gtk-2.0/gtkrc
    regexp: '^(\s+GtkScrollbar.+has.+stepper)'
    replace: '#\1'
    backup: yes
  become: yes
  when: ansible_distribution == "Ubuntu" and ansible_distribution_version == "14.04"
