---
- name: Remove deprecated indicator packages
  apt:
    name:
      # Replaced by xfce4-indicator-plugin
      - indicator-applet-complete
      # https://bugs.launchpad.net/ubuntu/+source/xfce4-indicator-plugin/+bug/1801724
      - indicator-application
      # This seems to be handled by xfce4-power-manager-plugins
      - indicator-power
      - indicator-printers
      # Replaced by xfce4-pulseaudio-plugin (https://bugs.launchpad.net/ubuntu/+source/xubuntu-meta/+bug/1781733)
      - indicator-sound
      # https://bugs.launchpad.net/ubuntu/+source/xfce4-indicator-plugin/+bug/1801724
      - xfce4-indicator-plugin
      # Replaced by xfce4-pulseaudio-plugin (https://bugs.launchpad.net/ubuntu/+source/xubuntu-meta/+bug/1781733)
      - xfce4-volumed
    state: absent
  become: yes
  notify: Restart Xfce panel
  when:
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_version == "18.04"

# Note that this will only fix apps which use Gtk 3
# https://bugs.launchpad.net/ubuntu/+source/shimmer-themes/+bug/881472
# https://unix.stackexchange.com/a/247758/14436
- name: Fix missing scrollbar arrow buttons with greybird theme
  copy:
    src: gtk.css
    dest: ~/.config/gtk-3.0/gtk.css
    force: no
  when:
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_version == "18.04"

# Ansible has a dconf module but it doesn't work in Ubuntu 16.04 because python-psutil is < 4.0
# For some reason this keeps getting set to 1 and it resets the indicator display to default
# http://askubuntu.com/a/858069/18665
# https://bugs.launchpad.net/ubuntu/+source/indicator-multiload/+bug/1740751
- name: Reset indicator-multiload indicator-expression-index
  shell: >
    dconf read /de/mh21/indicator-multiload/general/indicator-expression-index | grep '' &&
    dconf reset /de/mh21/indicator-multiload/general/indicator-expression-index || true
  register: result
  changed_when: result.stdout != ''
  when:
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_version == "16.04"

# https://bugs.launchpad.net/ubuntu/+source/console-setup/+bug/1612951
- name: Work around bug with /etc/default/keyboard
  lineinfile:
    path: ~/.xprofile
    line: 'setxkbmap -option compose:ralt'
    create: yes
  when:
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_version == "16.04"

# https://bugs.launchpad.net/ubuntu/+source/shimmer-themes/+bug/881472
- name: Fix missing scrollbar arrow buttons with greybird theme
  replace:
    path: /usr/share/themes/Greybird/gtk-3.0/gtk-widgets.css
    regexp: '^(\s+-GtkScrollbar.+has.+stepper)'
    replace: '#\1'
    backup: yes
  become: yes
  when:
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_version == "16.04"

- name: Check what version of Whisker Menu is installed
  shell: dpkg-query --showformat='${Version}' --show xfce4-whiskermenu-plugin
  changed_when: no
  check_mode: no
  failed_when: no
  register: result
  when:
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_version == "14.04"

# 14.04 comes with Whisker Menu which is often very slow to show the list of applications
- name: Install Whisker Menu 1.4
  apt:
    deb: http://mirrors.kernel.org/ubuntu/pool/universe/x/xfce4-whiskermenu-plugin/xfce4-whiskermenu-plugin_1.4.0-1ubuntu1~ubuntu14.04.1_amd64.deb
  become: yes
  when:
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_version == "14.04"
    - result.stdout is defined
    - result.stdout is version('1.4', '<')

# https://bugs.launchpad.net/ubuntu/+source/shimmer-themes/+bug/881472
- name: Fix missing scrollbar arrow buttons with greybird theme
  replace:
    path: /usr/share/themes/Greybird/gtk-2.0/gtkrc
    regexp: '^(\s+GtkScrollbar.+has.+stepper)'
    replace: '#\1'
    backup: yes
  become: yes
  when:
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_version == "14.04"
