---
- name: Set theme (Ubuntu 20.04)
  dconf:
    key: '{{ item.key }}'
    value: '{{ item.value }}'
  loop:
    - { key: /org/gnome/desktop/sound/theme-name, value: "'Yaru'" }
    - { key: /org/gnome/desktop/interface/cursor-theme, value: "'Yaru'" }
    - { key: /org/gnome/desktop/interface/gtk-theme, value: "'Yaru-dark'" }
    - { key: /org/gnome/desktop/interface/icon-theme, value: "'Yaru'" }
  when:
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_version is version('20.04', '=')
  notify: Restart Gnome Shell
  tags: [ubuntu-gnome]

- name: Set clock format
  dconf:
    key: '{{ item.key }}'
    value: '{{ item.value }}'
  loop:
    - { key: /org/gnome/desktop/interface/clock-format, value: "'24h'" }
    - { key: /org/gnome/desktop/interface/clock-show-date, value: 'false' }
    - { key: /org/gtk/Settings/FileChooser/clock-format, value: "'24h'" }
    # TODO: uncomment this if we decide to apply this task to 22.04; needs testing on 20.04
    # - { key: /org/gtk/gtk4/Settings/FileChooser/clock-format, value: "'24h'" }
  when:
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_version is version('20.04', '<=')
  tags: [ubuntu-gnome]

- name: Set keybindings
  dconf:
    key: '{{ item.key }}'
    value: '{{ item.value | string }}'
  loop:
    - {
        key: /org/gnome/desktop/wm/keybindings/move-to-workspace-down,
        value: "['<Control><Shift><Alt>Down', '<Shift><Super>Down']",
      }
    - {
        key: /org/gnome/desktop/wm/keybindings/move-to-workspace-left,
        value: "['<Control><Shift><Alt>Left', '<Shift><Super>Left']",
      }
    - {
        key: /org/gnome/desktop/wm/keybindings/move-to-workspace-right,
        value: "['<Control><Shift><Alt>Right', '<Shift><Super>Right']",
      }
    - {
        key: /org/gnome/desktop/wm/keybindings/move-to-workspace-up,
        value: "['<Control><Shift><Alt>Up', '<Shift><Super>Up']",
      }
    - {
        key: /org/gnome/desktop/wm/keybindings/switch-to-workspace-down,
        value: "['<Control><Alt>Down', '<Super>Down']",
      }
    - {
        key: /org/gnome/desktop/wm/keybindings/switch-to-workspace-left,
        value: "['<Control><Alt>Left', '<Super>Left']",
      }
    - {
        key: /org/gnome/desktop/wm/keybindings/switch-to-workspace-right,
        value: "['<Control><Alt>Right', '<Super>Right']",
      }
    - {
        key: /org/gnome/desktop/wm/keybindings/switch-to-workspace-up,
        value: "['<Control><Alt>Up', '<Super>Up']",
      }
  when:
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_version is version('20.04', '<=')
  tags: [ubuntu-gnome]

- name: Show minimize button
  dconf:
    key: /org/gnome/desktop/wm/preferences/button-layout
    value: "'appmenu:minimize,close'"
  when:
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_version is version('20.04', '<=')
  tags: [ubuntu-gnome]

- name: Hide home and trash icons on desktop
  dconf:
    key: '{{ item }}'
    value: 'false'
  loop:
    - /org/gnome/shell/extensions/desktop-icons/show-home
    - /org/gnome/shell/extensions/desktop-icons/show-trash
  when:
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_version is version('20.04', '<=')
  tags: [ubuntu-gnome]

  - name: Set file manager icon zoom level
  dconf:
    key: /org/gnome/nautilus/icon-view/default-zoom-level
    value: "'small'"
  when:
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_version is version('20.04', '<=')
  tags: [ubuntu-gnome]

- name: Enable user extensions
  dconf:
    key: /org/gnome/shell/disable-user-extensions
    value: 'false'
  when:
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_version is version('20.04', '<=')
  tags: [ubuntu-gnome]

- name: Set enabled extensions (Ubuntu 20.04)
  dconf:
    key: /org/gnome/shell/enabled-extensions
    value: "[\
      'desktop-icons@csoriano',
      'system-monitor@paradoxxx.zero.gmail.com',
      'ubuntu-appindicators@ubuntu.com',
      'ubuntu-dock@ubuntu.com'\
      ]"
  when:
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_version is version('20.04', '=')
  tags: [ubuntu-gnome]

# The default value (-1) is supposed to be the "primary monitor" but seems to be buggy, at least in 20.04
- name: Force dock to be on first monitor
  dconf:
    key: /org/gnome/shell/extensions/dash-to-dock/preferred-monitor
    value: '0'
  when:
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_version is version('20.04', '<=')
  tags: [ubuntu-gnome]

# ******************** Ubuntu 18.04 tasks ********************

- name: Install Pop!_OS repository
  apt_repository:
    repo: ppa:system76/pop
    update_cache: yes
  become: yes
  when:
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_version is version('18.04', '=')
  tags: [ubuntu-gnome]

- name: Install desired packages
  apt:
    name:
      - gnome-shell-extension-do-not-disturb
      - gnome-shell-extension-pop-battery-icon-fix
      - gnome-shell-extension-pop-suspend-button
      - pop-session
      - pop-theme
      - pop-wallpapers
      # This is a prerequisite for the ansible dconf module
      - python-psutil
    state: present
  become: yes
  notify: Restart Gnome Shell
  when:
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_version is version('18.04', '=')
  tags: [ubuntu-gnome]

- name: Set gtk-theme
  dconf:
    key: /org/gnome/desktop/interface/gtk-theme
    value: "'Pop-dark'"
  when:
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_version is version('18.04', '=')
  tags: [ubuntu-gnome]

- name: Hide trash icon on desktop
  dconf:
    key: /org/gnome/nautilus/desktop/trash-icon-visible
    value: 'false'
  when:
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_version is version('18.04', '<=')
  tags: [ubuntu-gnome]

- name: Set enabled extensions
  dconf:
    key: /org/gnome/shell/enabled-extensions
    value: "[\
      'batteryiconfix@kylecorry31.github.io',
      'donotdisturb@kylecorry31.github.io',
      'pop-suspend-button@system76.com',
      'system-monitor@paradoxxx.zero.gmail.com',
      'ubuntu-appindicators@ubuntu.com',
      'ubuntu-dock@ubuntu.com'\
      ]"
  when:
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_version is version('18.04', '=')
  tags: [ubuntu-gnome]

# https://askubuntu.com/q/1032624/18665
- name: Fix lock screen bug
  lineinfile:
    path: /etc/sysctl.conf
    regexp: '^fs.inotify.max_user_watches=.*'
    line: fs.inotify.max_user_watches=1048576
  become: yes
  when:
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_version is version('18.04', '=')
  tags: [ubuntu-gnome]

# ******************** Xubuntu to Ubuntu migration tasks ********************

- name: Remove undesired apps from autostart
  file:
    path: ~/.config/autostart/{{ item }}
    state: absent
  loop:
    - blueman.desktop
    - evolution-alarm-notify.desktop
    - google-chrome.desktop
    - indicator-multiload.desktop
    - indicator-sensors.desktop
    - light-locker.desktop
    - redshift-gtk.desktop
    - screensaver-settings.desktop
    - tracker-extract.desktop
    - tracker-miner-apps.desktop
    - tracker-miner-fs.desktop
    - tracker-miner-user-guides.desktop
    - tracker-store.desktop
    - xfce4-power-manager.desktop
    - xscreensaver.desktop
    - zeitgeist-datahub.desktop
  tags: [ubuntu-gnome]

# Many of these packages come from ubuntu-desktop and/or ubuntu-desktop-minimal, but we don't necessarily want all of those packages
- name: Install desired packages
  apt:
    name:
      - fonts-noto-color-emoji
      - gdm3
      - gnome-calculator
      - gnome-characters
      - gnome-control-center
      - gnome-screenshot
      - gnome-shell-extension-appindicator
      - gnome-shell-extension-desktop-icons
      - gnome-shell-extension-system-monitor
      - gnome-shell-extension-ubuntu-dock
      - nautilus
      # Not only does this show the Ubuntu logo during boot, without it a blank screen with a cursor will be shown
      # instead of the login page (which can be found by using Ctrl+Alt+F2 then Ctrl+Alt+F1)
      - plymouth-theme-spinner
      # Contains default settings for Gnome on Ubuntu; keybindings, etc
      - ubuntu-settings
      - yaru-theme-gnome-shell
      - yaru-theme-gtk
      - yaru-theme-icon
      - yaru-theme-sound
    state: present
  become: yes
  notify: Restart Gnome Shell
  tags: [ubuntu-gnome]

- name: Remove undesired packages
  apt:
    name:
      - doc-base
      - indicator*
      - lightdm*
      - pavucontrol
      - pinentry-gtk2
      - plymouth-theme-xubuntu*
      - redshift
      - xfce4*
      - xfdesktop4*
      - xterm
      - xubuntu*
    state: absent
    purge: yes
  become: yes
  tags: [ubuntu-gnome]

- name: Reset screen lock keybindings
  dconf:
    key: '{{ item }}'
    state: absent
  loop:
    - /org/gnome/settings-daemon/plugins/media-keys/logout
    - /org/gnome/settings-daemon/plugins/media-keys/screensaver
  tags: [ubuntu-gnome]
