---
- block:
    - name: Install Spotify repository
      apt_repository:
        repo: deb http://repository.spotify.com stable non-free
        state: present
        filename: spotify
      become: yes
      tags: [spotify]

  rescue:
    - name: Install Spotify GPG key
      apt_key:
        keyserver: hkp://keyserver.ubuntu.com:80
        id: 0DF731E45CE24F27EEEB1450EFDC8610341D9410
        state: present
      become: yes
      tags: [spotify]

    - name: Install Spotify repository
      apt_repository:
        repo: deb http://repository.spotify.com stable non-free
        state: present
        filename: spotify
      become: yes
      tags: [spotify]

# TODO: install Spotify using snap once snap support is added to ansible (https://www.spotify.com/us/download/linux/)
- name: Install Spotify
  apt:
    name: spotify-client
    state: present
  become: yes
  tags: [spotify]
