---
# snap is slow, clutters the mounts, and clutters the home folder
- name: Uninstall Spotify snap
  snap:
    name: spotify
    state: absent
  become: yes
  tags: [spotify]

# NOTE: This seems to have a bug where it often doesn't delete keys
# TODO: Can we delete this? Now that we're saving the Spotify GPG key to
#       /etc/apt/trusted.gpg.d/spotify.gpg are old keys still kept? Next time we update
#       the Spotify key, check if the old key is still kept somewhere, e.g.
#
#       ls /etc/apt/trusted.gpg.d/spotify*
#       apt-key list | grep -A 5 spotify
#
#       If not, then we can delete this task. If it is, then we may need to replace this
#       task with a file removal task as this task already seems to be buggy and
#       apparently apt-key is deprecated.
- name: Clean up old Spotify GPG keys
  ansible.builtin.apt_key:
    id: '{{ item }}'
    state: absent
  with_items:
    - 0D811D58
    - 341D9410
    - 48BF1C90
    - 63CBEEC9
    - B312C643
    - E27409F5
    - F9A21197
  become: yes
  tags: [spotify]

# TODO: Next time we replace the Spotify key, see the TODO in the previous task
# NOTE: If this task fails, get the latest key URL from https://www.spotify.com/us/download/linux/
- name: Install Spotify GPG key
  ansible.builtin.apt_key:
    url: https://download.spotify.com/debian/pubkey_6224F9941A8AA6D1.gpg
    keyring: /etc/apt/trusted.gpg.d/spotify.gpg
  become: yes
  tags: [spotify]

- name: Install Spotify repository
  apt_repository:
    repo: deb http://repository.spotify.com stable non-free
    state: present
    filename: spotify
    update_cache: yes
  become: yes
  tags: [spotify]

- name: Install Spotify
  apt:
    name: spotify-client
    state: latest
  become: yes
  tags: [spotify]

# NOTE: If we run into an issue again where Spotify freezes where there probably should've been an ad, use mitmproxy to debug
# https://www.theverge.com/2019/2/7/18215845/spotify-ad-blockers-terms-of-service
# To set up debugging of DNS logs (prerequisite for below): https://unix.stackexchange.com/a/432077/14436
#   To undo DNS debugging: sudo systemctl revert systemd-resolved
# To see which domains are being blocked:
# 1. Make a note of when Spotify was opened (in case it's doing DNS caching, it might only do DNS request once)
# 2. Clear old logs
#    sudo journalctl --vacuum-time=1d
# 3. List all hosts that have been looked up that are blocked in /etc/hosts
#    for hostname in $(sudo journalctl -u systemd-resolved | grep "Looking up RR" | awk '{print $10}' | sort -u); do grep "\s$hostname$" /etc/hosts | egrep -v '^#'; done
# 4. See when that host was actually blocked
#    sudo journalctl -u systemd-resolved | grep hostname
- name: Make sure Spotify ads aren't blocked
  lineinfile:
    path: /etc/hosts
    regexp: '^#?{{ item | regex_escape() }}'
    line: '#{{ item }}'
  loop:
    - 0.0.0.0 pagead.l.doubleclick.net
    - 0.0.0.0 spclient.wg.spotify.com
  become: yes
  tags: [spotify]
