---
# snap is slow, clutters the mounts, and clutters the home folder
- name: Uninstall Spotify snap
  snap:
    name: spotify
    state: absent
  become: yes
  tags: [spotify]

- block:
    - name: Install Spotify repository
      apt_repository:
        repo: deb http://repository.spotify.com stable non-free
        state: present
        filename: spotify
        update_cache: yes
      become: yes
      tags: [spotify]

  rescue:
    # TODO: This doesn't actually seem to do anything...
    - name: Clean up old Spotify GPG keys
      apt_key:
        id: '{{ item }}'
        state: absent
      with_items:
        - 0DF731E45CE24F27EEEB1450EFDC8610341D9410
        - 931FF8E79F0876134EDDBDCCA87FF9DF48BF1C90
        - 8FD3D9A8D3800305A9FFF259D1742AD60D811D58
      become: yes
      tags: [spotify]

    - name: Install Spotify GPG key
      apt_key:
        url: https://download.spotify.com/debian/pubkey_5E3C45D7B312C643.gpg
        state: present
      become: yes
      tags: [spotify]

    - name: Install Spotify repository
      apt_repository:
        repo: deb http://repository.spotify.com stable non-free
        state: present
        filename: spotify
        update_cache: yes
      become: yes
      tags: [spotify]

- name: Install Spotify
  apt:
    name: spotify-client
    state: latest
  become: yes
  tags: [spotify]

- name: Block Spotify images
  blockinfile:
    path: /etc/hosts
    # Use a unique marker, otherwise it will conflict with other blockinfile instances for /etc/hosts
    marker: '# {mark} ANSIBLE MANAGED BLOCK - Block Spotify images'
    block: |
      0.0.0.0 dailymix-images.scdn.co
      0.0.0.0 i.scdn.co
      0.0.0.0 mosaic.scdn.co
      0.0.0.0 pl.scdn.co
      0.0.0.0 seed-mix-image.spotifycdn.com
      0.0.0.0 seeded-session-images.scdn.co
      0.0.0.0 t.scdn.co
      0.0.0.0 thisis-images.scdn.co
  become: yes
  tags: [spotify]

# NOTE: If we run into an issue again where Spotify freezes where there probably should've been an ad, use mitmproxy to debug
# https://www.theverge.com/2019/2/7/18215845/spotify-ad-blockers-terms-of-service
# To set up debugging of DNS logs (prerequisite for below): https://unix.stackexchange.com/a/432077/14436
#   To undo DNS debugging: sudo systemctl revert systemd-resolved
# To see which domains are being blocked:
# 1. Make a note of when Spotify was opened (in case it's doing DNS caching, it might only do DNS request once)
# 2. Clear old logs
#    sudo journalctl --vacuum-time=1d
# 3. List all hosts that have been looked up that are blocked in /etc/hosts
#    for hostname in $(sudo journalctl -u systemd-resolved | grep "Looking up RR" | awk '{print $10}' | sort -u); do grep "\s$hostname$" /etc/hosts | egrep -v '^#'; done
# 4. See when that host was actually blocked
#    sudo journalctl -u systemd-resolved | grep hostname
- name: Make sure Spotify ads aren't blocked
  lineinfile:
    path: /etc/hosts
    regexp: '^#?{{ item | regex_escape() }}'
    line: '#{{ item }}'
  loop:
    - 0.0.0.0 pagead.l.doubleclick.net
    - 0.0.0.0 spclient.wg.spotify.com
  become: yes
  tags: [spotify]
