---
# https://askubuntu.com/a/100228/18665
- name: Restart Gnome Shell
  # Restart Teams as well if it was running since restarting Gnome Shell will kill it
  shell: >
    teams_running=$(ps -ef | grep [/]usr/share/teams/teams);
    killall -3 gnome-shell;
    if [ -n "$teams_running" ]; then
      teams --disable-features=HardwareMediaKeyHandling
    fi
