---
- name: Install git
  apt:
    name: git
    state: present
  become: yes
  tags: [git]

- name: Copy global .gitconfig
  copy:
    src: .gitconfig
    dest: ~/.gitconfig
    backup: yes
  tags: [git]

- name: Make sure ~/workspace/personal exists
  file:
    path: ~/workspace/personal
    state: directory
  tags: [git]

- name: Copy personal .gitconfig
  copy:
    src: personal/.gitconfig
    dest: ~/workspace/personal/.gitconfig
    backup: yes
  tags: [git]

- name: Make sure ~/workspace/work exists
  file:
    path: ~/workspace/work
    state: directory
  tags: [git]

- name: Copy work .gitconfig
  copy:
    src: work/.gitconfig
    dest: ~/workspace/work/.gitconfig
    backup: yes
  tags: [git]

# Git will fall back to core.editor in .gitconfig, then VISUAL, then EDITOR, so this isn't necessary
- name: Unset default git editor
  lineinfile:
    path: ~/.bashrc
    regexp: '^export GIT_EDITOR=.*'
    state: absent
  tags: [git]
