---
- name: Install Deja Dup
  apt:
    name:
      - deja-dup
    state: present
  become: yes
  tags: [deja-dup]

- name: Set up backups for user 1
  import_tasks: user-1-backups.yml
  tags: [deja-dup]
