---
- import_tasks: clamav.yml

- name: Run tasks for Ubuntu 14.04
  import_tasks: ubuntu-1404.yml
  when:
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_version == "14.04"

- name: Install desired packages
  apt:
    name:
      - brasero
      - fail2ban
      - ldap-utils
    state: present
  become: yes

- name: Configure fail2ban
  copy:
    src: jail.local
    dest: /etc/fail2ban/jail.local
    mode: 0444
  become: yes
  notify: Restart fail2ban

- name: Set Pidgin to autostart
  file:
    src: /usr/share/applications/pidgin.desktop
    dest: ~/.config/autostart/pidgin.desktop
    state: link

- name: Configure cups server
  lineinfile:
    path: /etc/cups/cups-browsed.conf
    line: BrowsePoll {{ cups_server }}
  become: yes
  notify: Restart cups-browsed

- name: Configure cups user
  lineinfile:
    path: ~/.profile
    line: export CUPS_USER={{ cups_user }}

- name: Add firewall rules
  ufw:
    rule: "{{ item.rule }}"
    port: "{{ item.port }}"
    proto: "{{ item.proto }}"
    src: "{{ item.src }}"
  loop: "{{ firewall_add }}"
  become: yes

- name: Delete firewall rules
  ufw:
    rule: "{{ item.rule }}"
    port: "{{ item.port }}"
    proto: "{{ item.proto }}"
    src: "{{ item.src }}"
    delete: yes
  loop: "{{ firewall_delete }}"
  become: yes

- name: Set default audio output device
  lineinfile:
    path: /etc/pulse/default.pa
    line: set-default-sink 0
  become: yes
  notify: Remove ~/.config/pulse

- name: Get the power manager plugin ID
  shell: xfconf-query -lv -c xfce4-panel | grep power-manager-plugin | awk '{print $1}'
  register: power_manager_plugin_id
  changed_when: no
  check_mode: no

- name: Remove the power manager plugin
  # This removes the plugin from xfconf, but not the list of active plugins
  shell: "xfconf-query -c xfce4-panel -p {{ power_manager_plugin_id.stdout }} -r"
  # Restarting the panel will also remove the plugin from the list of active plugins
  notify: Restart Xfce panel
  when: power_manager_plugin_id.stdout is defined and power_manager_plugin_id.stdout != ""

# https://bugs.launchpad.net/ubuntu/+source/policykit-1/+bug/1470235
- name: Configure cron job to report polkitd memory usage
  cron:
    name: Report polkitd memory usage
    special_time: daily
    job: /bin/bash -c 'if [ $(ps aux | grep -v grep | grep polkitd | awk "{print \$6}") -gt 100000 ]; then ps aux | grep -v grep | grep polkitd > ~/Desktop/polkitd-$(date +\%Y\%m\%d).txt; fi'
