---
- name: Run tasks for Ubuntu 14.04
  include: ubuntu-1404.yml
  when:
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_version == "14.04"

- name: Install desired packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - brasero
    - fail2ban
    - ldap-utils
    - thunderbird
    - thunderbird-locale-fr
  become: yes

- name: Configure fail2ban
  copy:
    src: jail.local
    dest: /etc/fail2ban/jail.local
    mode: 0444
  become: yes
  notify: Restart fail2ban

- name: Install VirtualBox GPG key
  apt_key:
    url: https://www.virtualbox.org/download/oracle_vbox.asc
    state: present
  become: yes

- name: Get Ubuntu release codename
  shell: lsb_release -cs
  changed_when: no
  check_mode: no
  register: result

- name: Install VirtualBox repository
  apt_repository:
    repo: "deb http://download.virtualbox.org/virtualbox/debian {{ result.stdout }} contrib"
    state: present
    filename: virtualbox
  become: yes

- name: Install VirtualBox
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - dkms
    - virtualbox-5.2
  become: yes

- name: Set Pidgin to autostart
  file:
    src: /usr/share/applications/pidgin.desktop
    dest: ~/.config/autostart/pidgin.desktop
    state: link

- name: Copy Thunderbird .desktop file
  copy:
    src: /usr/share/applications/thunderbird.desktop
    dest: ~/.local/share/applications/thunderbird.desktop
    force: no

- name: Set Thunderbird language
  replace:
    path: ~/.local/share/applications/thunderbird.desktop
    regexp: '^Exec=thunderbird'
    replace: 'Exec=env LC_ALL=fr_CA.utf8 thunderbird'
    backup: yes

# Thunderbird needs a simpler entry for autostart or it won't work, in particular for Xfce
- name: Set Thunderbird to autostart
  copy:
    src: thunderbird.desktop
    dest: ~/.config/autostart/thunderbird.desktop

- name: Ignore certificate when using ldapsearch
  lineinfile:
    path: /etc/ldap/ldap.conf
    line: TLS_REQCERT never
  become: yes

- name: Configure cups server
  lineinfile:
    path: /etc/cups/cups-browsed.conf
    line: BrowsePoll {{ cups_server }}
  become: yes
  notify: Restart cups-browsed

- name: Configure cups user
  lineinfile:
    path: ~/.profile
    line: export CUPS_USER={{ cups_user }}
