---
# NOTE: The Teams app for Linux was retired in favour of a PWA
# - Teams in Firefox is meh
#   - A lot of disconnects during video calls
#   - Status changes to away when the mouse isn't over the Teams tab in the browser
# - Could try the PWA on Chrome
# - There's also this unofficial client: https://github.com/IsmaelMartinez/teams-for-linux

# TODO: Install teams-for-linux
# https://github.com/IsmaelMartinez/teams-for-linux

- name: Copy custom autostart file
  copy:
    src: /usr/share/applications/teams-for-linux.desktop
    dest: ~/.config/autostart/teams-for-linux.desktop
    # Don't overwrite the file since we'll modify it in the next step
    force: no
  when: teams_autostart
  tags: [teams]

# TODO: Only start Teams on weekdays
# - name: Disable hardware media key handling when Teams is automatically started
#   replace:
#     path: ~/.config/autostart/teams-custom.desktop
#     regexp: '^Exec=teams %U'
#     replace: 'Exec=teams --disable-features=HardwareMediaKeyHandling %U'
#   when: teams_autostart
#   tags: [teams]

- name: Remove old autostart file
  file:
    path: ~/.config/autostart/teams-custom.desktop
    state: absent
  tags: [teams]

- name: Remove custom autostart file
  file:
    path: ~/.config/autostart/teams-for-linux.desktop
    state: absent
  when: not teams_autostart
  tags: [teams]
