---
- name: Install Microsoft GPG key
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    keyring: /etc/apt/trusted.gpg.d/microsoft.gpg
  become: yes
  tags: [teams]

- name: Install Teams repository
  apt_repository:
    repo: deb [arch=amd64] https://packages.microsoft.com/repos/ms-teams stable main
    state: present
    filename: teams
    update_cache: yes
  become: yes
  tags: [teams]

- name: Install Teams
  apt:
    name: teams
    state: latest
  become: yes
  tags: [teams]

- name: Copy custom desktop file
  copy:
    src: /usr/share/applications/teams.desktop
    dest: ~/.local/share/applications/teams.desktop
    # Don't overwrite the file since we'll modify it in the next step
    force: no
  tags: [teams]

# Work around this bug: https://feedbackportal.microsoft.com/feedback/idea/b0668d5e-272e-ec11-b6e6-00224827bbc2
- name: Disable hardware media key handling when manually opening Teams
  replace:
    path: ~/.local/share/applications/teams.desktop
    regexp: '^Exec=teams %U'
    replace: 'Exec=teams --disable-features=HardwareMediaKeyHandling %U'
  tags: [teams]

# This actually needs to be set from within the application (3 dots menu > Settings > Auto-start application) but we'll
# leave it here as a reminder to disable the default Teams autostart, which we need to do because even if we want
# autostart, we need to use a custom autostart file (see below)
- name: Disable default autostart
  file:
    path: ~/.config/autostart/teams.desktop
    state: absent
  tags: [teams]

# We have to use a custom desktop file because the default one (teams.desktop) is managed by the Teams app and will be
# overwritten
- name: Copy custom autostart file
  copy:
    src: /usr/share/applications/teams.desktop
    dest: ~/.config/autostart/teams-custom.desktop
    # Don't overwrite the file since we'll modify it in the next step
    force: no
  when: teams_autostart
  tags: [teams]

# Work around this bug: https://feedbackportal.microsoft.com/feedback/idea/b0668d5e-272e-ec11-b6e6-00224827bbc2
- name: Disable hardware media key handling when Teams is automatically started
  replace:
    path: ~/.config/autostart/teams-custom.desktop
    regexp: '^Exec=teams %U'
    replace: 'Exec=teams --disable-features=HardwareMediaKeyHandling %U'
  when: teams_autostart
  tags: [teams]

- name: Remove custom autostart file
  file:
    path: ~/.config/autostart/teams-custom.desktop
    state: absent
  when: not teams_autostart
  tags: [teams]
