---
# NOTE: The Teams app for Linux was retired in favour of a PWA
# - Teams in Firefox is meh
#   - A lot of disconnects during video calls
#   - Status changes to away when the mouse isn't over the Teams tab in the browser
# - Could try the PWA on Chrome
# - There's also this unofficial client: https://github.com/IsmaelMartinez/teams-for-linux

- name: Remove old autostart file
  file:
    path: ~/.config/autostart/teams-custom.desktop
    state: absent
  tags: [teams]

# TODO: Install teams-for-linux
# https://github.com/IsmaelMartinez/teams-for-linux

- name: Copy custom autostart file
  copy:
    src: /usr/share/applications/teams-for-linux.desktop
    dest: ~/.config/autostart/teams-for-linux.desktop
    # Don't overwrite the file since we'll modify it in the next step
    force: no
  when: teams_autostart
  tags: [teams]

- name: Only autostart Teams on weekdays between 8:00 - 17:00
  replace:
    path: ~/.config/autostart/teams-for-linux.desktop
    regexp: '^Exec=.*'
    replace: "Exec=bash -c 'h=$(date +%-H); [[ $(date +%u) -le 5 && $h -ge 8 && $h -lt 17 ]] && exec /opt/teams-for-linux/teams-for-linux %U'"
  when: teams_autostart
  tags: [teams]

- name: Remove custom autostart file
  file:
    path: ~/.config/autostart/teams-for-linux.desktop
    state: absent
  when: not teams_autostart
  tags: [teams]
