---
# Normally Gnome remembers the last setting; this will disable it by default (https://askubuntu.com/a/1060096/18665)
- name: Disable bluetooth auto power on
  lineinfile:
    path: ~/.profile
    line: 'rfkill block bluetooth'
  when: "'ubuntu-gnome' in ansible_role_names"
  tags: [office-laptop]

- name: Install smbios-utils
  apt:
    name: smbios-utils
  become: yes
  tags: [office-laptop]

- name: Get battery charging configuration
  shell: smbios-battery-ctl --get-charging-cfg
  changed_when: no
  check_mode: no
  register: result
  become: yes
  tags: [office-laptop]

- name: Set charging mode to custom
  shell: smbios-battery-ctl --set-charging-mode=custom
  when: "result.stdout_lines[0] != 'Charging mode: custom'"
  become: yes
  tags: [office-laptop]

# Upper bound must be at least 56 as per https://github.com/dell/libsmbios/issues/101
- name: Set custom charge interval
  shell: smbios-battery-ctl --set-custom-charge-interval=75 80
  when: "result.stdout_lines[1] is not defined or result.stdout_lines[1] != 'Charging interval: (75, 80)'"
  become: yes
  tags: [office-laptop]

# This overrides the Gnome battery icon to match the custom charge interval so that when
# the maximum charge is reached, Gnome won't show that the battery is still charging
#
# NOTE:
# - If this is changed, reinstall yaru-theme-icon to restore the original icons (sudo apt install --reinstall yaru-theme-icon)
#   - We could also just add that command as a notify action of the previous task ...
- name: Override battery icon when fully charged
  copy:
    src: /usr/share/icons/Yaru/scalable/status/battery-level-{{ item }}-symbolic.svg
    dest: /usr/share/icons/Yaru/scalable/status/battery-level-{{ item }}-charging-symbolic.svg
    force: yes
  loop:
    # Icons are available at every power of 10, so we need to modify the icon for the min and max charging intervals, rounding down
    - 70
    - 80
  become: yes
  notify: Restart Gnome Shell
  tags: [office-laptop]

- name: Install missing Intel firmware
  get_url:
    url: 'https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/plain/{{ item }}'
    dest: '/lib/firmware/{{ item }}'
  loop:
    # This list was generated using output from sudo update-initramfs -u
    - i915/adlp_dmc_ver2_14.bin
    - i915/adlp_guc_69.0.3.bin
    - i915/bxt_guc_49.0.1.bin
    - i915/bxt_guc_69.0.3.bin
    - i915/cml_guc_49.0.1.bin
    - i915/cml_guc_69.0.3.bin
    - i915/dg1_dmc_ver2_02.bin
    - i915/dg1_guc_69.0.3.bin
    - i915/ehl_guc_49.0.1.bin
    - i915/ehl_guc_69.0.3.bin
    - i915/glk_guc_49.0.1.bin
    - i915/glk_guc_69.0.3.bin
    - i915/icl_guc_49.0.1.bin
    - i915/icl_guc_69.0.3.bin
    - i915/kbl_guc_49.0.1.bin
    - i915/kbl_guc_69.0.3.bin
    - i915/skl_guc_49.0.1.bin
    - i915/skl_guc_69.0.3.bin
    - i915/tgl_guc_49.0.1.bin
    - i915/tgl_guc_69.0.3.bin
    - i915/tgl_huc_7.5.0.bin
  become: yes
  notify: Update initramfs
  tags: [office-laptop]
