---
# Normally Gnome remembers the last setting; this will disable it by default (https://askubuntu.com/a/1060096/18665)
- name: Disable bluetooth auto power on
  lineinfile:
    path: ~/.profile
    line: 'rfkill block bluetooth'
  when: "'ubuntu-gnome' in ansible_role_names"
  tags: [office-laptop]

- name: Install smbios-utils
  apt:
    name: smbios-utils
  become: yes
  tags: [office-laptop]

- name: Get battery charging configuration
  shell: smbios-battery-ctl --get-charging-cfg
  changed_when: no
  check_mode: no
  register: result
  become: yes
  tags: [office-laptop]

- name: Set charging mode to custom
  shell: smbios-battery-ctl --set-charging-mode=custom
  when: "result.stdout_lines[0] != 'Charging mode: custom'"
  become: yes
  tags: [office-laptop]

# Upper bound must be at least 56 as per https://github.com/dell/libsmbios/issues/101
- name: Set custom charge interval
  # TODO: bump this back down to 51 56 if we can figure out how to do S3 sleep...
  # https://01.org/linuxgraphics/gfx-docs/drm/admin-guide/pm/sleep-states.html
  # cat /var/log/kern.log* | grep ACPI | grep support
  # cat /sys/power/state
  # cat /sys/power/mem_sleep
  # https://www.reddit.com/r/Dell/comments/onaavu/dell_latitude_5420_suspend_deep_sleep_problem_in/
  # https://www.reddit.com/r/Dell/comments/hla8yk/how_to_enable_s3_deep_sleep_on_xps_17_9700_in/
  # https://www.dell.com/support/kbdoc/en-in/000129781/steps-for-fixing-windows-computers-that-do-not-wake-up-or-resume-from-suspend-or-hibernate-mode-but-will-power-on
  shell: smbios-battery-ctl --set-custom-charge-interval=55 60
  when: "result.stdout_lines[1] is not defined or result.stdout_lines[1] != 'Charging interval: (55, 60)'"
  become: yes
  tags: [office-laptop]

- name: Install missing Intel firmware
  get_url:
    url: 'https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/plain/{{ item }}'
    dest: '/lib/firmware/{{ item }}'
  loop:
    # This list was generated using output from sudo update-initramfs -u
    - i915/bxt_guc_49.0.1.bin
    - i915/cml_guc_49.0.1.bin
    - i915/dg1_dmc_ver2_02.bin
    - i915/ehl_guc_49.0.1.bin
    - i915/glk_guc_49.0.1.bin
    - i915/icl_guc_49.0.1.bin
    - i915/kbl_guc_49.0.1.bin
    - i915/skl_guc_49.0.1.bin
    - i915/tgl_guc_49.0.1.bin
    - i915/tgl_huc_7.5.0.bin
  become: yes
  notify: Update initramfs
  tags: [office-laptop]
