---
- name: Get Ubuntu release codename
  shell: lsb_release -cs
  changed_when: no
  check_mode: no
  register: release
  tags: [virtualbox]

- block:
    - name: Install VirtualBox repository
      apt_repository:
        repo: "deb http://download.virtualbox.org/virtualbox/debian {{ release.stdout }} contrib"
        state: present
        filename: virtualbox
        update_cache: yes
      become: yes
      tags: [virtualbox]

  rescue:
    - name: Install VirtualBox GPG key
      apt_key:
        url: https://www.virtualbox.org/download/oracle_vbox.asc
        state: present
      become: yes
      when:
        - ansible_distribution == "Ubuntu"
        - ansible_distribution_version is version('14.04', '<=')
      tags: [virtualbox]

    - name: Install VirtualBox GPG key
      apt_key:
        url: https://www.virtualbox.org/download/oracle_vbox_2016.asc
        state: present
      become: yes
      when:
        - ansible_distribution == "Ubuntu"
        - ansible_distribution_version is version('16.04', '>=')
      tags: [virtualbox]

    - name: Install VirtualBox repository
      apt_repository:
        repo: "deb http://download.virtualbox.org/virtualbox/debian {{ release.stdout }} contrib"
        state: present
        filename: virtualbox
        update_cache: yes
      become: yes
      tags: [virtualbox]

- name: Install VirtualBox
  apt:
    name: "virtualbox-{{ virtualbox_version }}"
    state: latest
  become: yes
  ignore_errors: '{{ ansible_check_mode }}'
  tags: [virtualbox]

# The extension pack requires a paid license for anything other than personal or evaluation use
- name: Make sure extension pack is uninstalled
  import_tasks: uninstall-extension-pack.yml
