---
- name: Check if VirtualBox is installed
  shell: dpkg -l virtualbox-{{ virtualbox_version }}
  changed_when: no
  check_mode: no
  failed_when: no
  register: result
  tags: [virtualbox, virtualbox-install]

- name: Include VirtualBox install tasks
  # Use dynamic include so skipped tasks won't show in output
  include_tasks: install.yml
  when: result.rc is defined and result.rc != 0
  tags: [virtualbox, virtualbox-install]
