---
# VirtualBox needs to compile a kernel module, and for this it needs the same version of
# gcc that was used to compile the kernel
- name: Get the version of gcc used to compile the kernel
  shell: cat /proc/version | grep -Po 'gcc-\d+'
  changed_when: no
  check_mode: no
  register: gcc_version
  tags: [virtualbox]

- name: Install gcc
  apt:
    name: '{{ gcc_version.stdout }}'
  become: yes
  tags: [virtualbox]

- name: Get Ubuntu release codename
  shell: lsb_release -cs
  changed_when: no
  check_mode: no
  register: release
  tags: [virtualbox]

- name: Install VirtualBox GPG key
  apt_key:
    url: https://www.virtualbox.org/download/oracle_vbox_2016.asc
    keyring: /etc/apt/trusted.gpg.d/virtualbox.gpg
  become: yes
  tags: [virtualbox]

# This is needed to remove the http:// entry, otherwise a duplicate entry is added
- name: Remove old VirtualBox repository
  apt_repository:
    repo: 'deb http://download.virtualbox.org/virtualbox/debian {{ release.stdout }} contrib'
    state: absent
    filename: virtualbox
  become: yes
  tags: [virtualbox]

- name: Install VirtualBox repository
  apt_repository:
    repo: 'deb [arch=amd64] https://download.virtualbox.org/virtualbox/debian {{ release.stdout }} contrib'
    state: present
    filename: virtualbox
    update_cache: yes
  become: yes
  tags: [virtualbox]

- name: Install VirtualBox
  apt:
    name: 'virtualbox-{{ virtualbox_version }}'
    state: latest
  become: yes
  ignore_errors: '{{ ansible_check_mode }}'
  tags: [virtualbox]

- name: Add user to vboxusers group
  user:
    name: '{{ ansible_user_id }}'
    groups: vboxusers
    append: yes
  become: yes
  tags: [virtualbox]

# The extension pack requires a paid license for anything other than personal or evaluation use
- name: Make sure extension pack is uninstalled
  import_tasks: uninstall-extension-pack.yml
