---
# TODO: Install Ansible via pip? https://docs.ansible.com/ansible/latest/installation_guide/intro_installation.html#pip-install
#       For now, we'll leave the actual installation of Ansible out of this playbook to
#       allow for different methods of installing it, since it will need to be installed
#       before running this role anyway. So this is more for managing dependencies.

- name: Install desired packages
  apt:
    name:
      # Prerequisite for the ansible xattr module
      - attr
      # Prerequisite for the ansible apt module
      - python3-apt
      # Prerequisite for the ansible dconf module
      - python3-psutil
    state: present
  become: yes
  when:
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_version is version('20.04', '>=')
  tags: [ansible]
