---
- name: Install desired packages
  apt:
    name:
      - ansible
      # Prerequisite for the ansible xattr module
      - attr
      # Prerequisite for the ansible apt module
      - python3-apt
      # Prerequisite for the ansible dconf module
      - python3-psutil
    state: present
  become: yes
  notify: Restart Gnome Shell
  when:
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_version is version('20.04', '>=')
  tags: [ansible]
