---
- name: Check if Dropbox is installed
  shell: dpkg -l dropbox
  changed_when: no
  check_mode: no
  failed_when: no
  register: result
  tags: [dropbox]

- name: Install Dropbox
  apt:
    deb: https://www.dropbox.com/download?plat=lnx.x86_64
  become: yes
  when: result.rc is defined and result.rc != 0
  tags: [dropbox]

- name: Disable broken Dropbox autostart
  shell: dropbox autostart n
  args:
    removes: ~/.config/autostart/dropbox.desktop
  tags: [dropbox]

- name: Copy fixed Dropbox autostart
  copy:
    src: dropbox-fixed.desktop
    dest: ~/.config/autostart
  tags: [dropbox]
