---
- name: Check if Dropbox is installed
  shell: dpkg -l dropbox
  changed_when: no
  check_mode: no
  failed_when: no
  register: result
  tags: [dropbox]

- name: Install Dropbox
  apt:
    deb: https://www.dropbox.com/download?dl=packages/ubuntu/dropbox_2018.11.28_amd64.deb
  become: yes
  when: result.rc is defined and result.rc != 0
  tags: [dropbox]

- name: Disable broken Dropbox autostart
  shell: dropbox autostart n
  args:
    removes: ~/.config/autostart/dropbox.desktop
  tags: [dropbox]

- name: Copy fixed Dropbox autostart
  copy:
    src: dropbox-fixed.desktop
    dest: ~/.config/autostart
  tags: [dropbox]

- name: Get installed version of Dropbox
  set_fact:
    dropbox_installed_version: "{{ lookup('file', '~/.dropbox-dist/VERSION') }}"
  tags: [dropbox]

- name: Get latest version of Dropbox
  uri:
    url: https://www.dropbox.com/download?plat=lnx.x86_64
    # Don't download the file just yet
    method: HEAD
  register: response
  tags: [dropbox]

# Dropbox doesn't seem to always be able to upgrade itself
# https://www.dropboxforum.com/t5/Installs-integrations/Stuck-on-quot-upgrading-dropbox-quot/td-p/284217
- name: Upgrade Dropbox
  import_tasks: upgrade.yml
  when: response.url | basename != 'dropbox-lnx.x86_64-' ~ dropbox_installed_version ~ '.tar.gz'
  tags: [dropbox]
