---
- name: Check if Dropbox is installed
  shell: dpkg -l dropbox
  changed_when: no
  check_mode: no
  failed_when: no
  register: result
  tags: [dropbox]

- name: Install dependencies
  apt:
    name: python-gpg
    state: present
  become: yes
  tags: [dropbox]

- name: Install Dropbox
  apt:
    deb: https://www.dropbox.com/download?dl=packages/ubuntu/dropbox_2018.11.28_amd64.deb
  become: yes
  when: result.rc is defined and result.rc != 0
  tags: [dropbox]

- name: Disable default autostart
  shell: dropbox autostart n
  args:
    removes: ~/.config/autostart/dropbox.desktop
  tags: [dropbox]

- name: Clean up old custom autostart files
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - ~/.config/autostart/dropbox-delayed.desktop
    - ~/.config/autostart/dropbox-fixed.desktop
  tags: [dropbox]

# We have to use a custom desktop file because the default one (dropbox.desktop) is managed by the Dropbox app and will
# be deleted or overwritten
- name: Copy custom autostart file
  copy:
    src: /usr/share/applications/dropbox.desktop
    dest: ~/.config/autostart/dropbox-custom.desktop
    force: no
  tags: [dropbox]

  # Dropbox hijacks io when it's first starting up, even with renice. So wait a bit before starting it
- name: Wait a bit before automatically starting Dropbox
  replace:
    path: ~/.config/autostart/dropbox-custom.desktop
    regexp: '^Exec=.*'
    replace: "Exec=sh -c 'sleep 300; dropbox start -i && sleep 5 && renice +19 $(pgrep dropbox)'"
  tags: [dropbox]

# TODO: is this still needed?
# - name: Get installed version of Dropbox
#   set_fact:
#     dropbox_installed_version: "{{ lookup('file', '~/.dropbox-dist/VERSION') }}"
#   tags: [dropbox]

# - name: Get latest version of Dropbox
#   uri:
#     url: https://www.dropbox.com/download?plat=lnx.x86_64
#     # Don't download the file just yet
#     method: HEAD
#   register: response
#   tags: [dropbox]

# # Dropbox doesn't seem to always be able to upgrade itself
# # https://www.dropboxforum.com/t5/Installs-integrations/Stuck-on-quot-upgrading-dropbox-quot/td-p/284217
# - name: Upgrade Dropbox
#   import_tasks: upgrade.yml
#   when: response.url | basename != 'dropbox-lnx.x86_64-' ~ dropbox_installed_version ~ '.tar.gz'
#   tags: [dropbox]
