---
# TODO: add steps to install Wine (install prerequisites, install GPG key, install repo, install package(s))

# https://wiki.winehq.org/FAQ#How_do_I_clean_the_Open_With_List.3F
- name: Remove Wine MIME associations
  file: path={{ item }}
    state=absent
  with_fileglob:
    - ~/.local/share/mime/packages/x-wine*
    - ~/.local/share/applications/wine-extension*
    - ~/.local/share/icons/hicolor/16x16/apps/application-x-wine-extension*
    - ~/.local/share/icons/hicolor/24x24/apps/application-x-wine-extension*
    - ~/.local/share/icons/hicolor/32x32/apps/application-x-wine-extension*
    - ~/.local/share/icons/hicolor/48x48/apps/application-x-wine-extension*
    - ~/.local/share/icons/hicolor/64x64/apps/application-x-wine-extension*
    - ~/.local/share/icons/hicolor/128x128/apps/application-x-wine-extension*
    - ~/.local/share/icons/hicolor/256x256/apps/application-x-wine-extension*
    - ~/.local/share/mime/application/x-wine-extension*
  tags: [wine]

- name: Find all wine.inf files
  find:
    paths:
      - ~/.local/share/lutris/runners/wine/
      # These are commented because Proton doesn't seem to create MIME associations
      # Proton GE
      # - ~/.local/share/Steam/compatibilitytools.d/
      # Proton
      # - ~/.local/share/Steam/steamapps/common/
      # Wine from Wine PPA
      - /opt/wine-stable/share/wine/
      # Wine from ubuntu
      - /usr/share/wine/
    patterns: wine.inf
    recurse: true
  register: result
  tags: [wine]

# https://askubuntu.com/a/400430/18665
- name: Prevent Wine from creating new MIME associations
  replace:
    path: '{{ item.path }}'
    regexp: '^HKLM,%CurrentVersion%\\RunServices,"winemenubuilder".*'
    replace: 'HKLM,%CurrentVersion%\\RunServices,"winemenubuilder",2,"%11%\\winemenubuilder.exe -r"'
  loop: '{{ result.files }}'
  failed_when: false
  become: true
  tags: [wine]
