---
- name: Install Safe Eyes
  apt:
    name: safeeyes
    state: present
  become: yes
  tags: [safeeyes]

- name: Check if ~/.config/safeeyes exists
  stat:
    path: ~/.config/safeeyes
  register: result
  tags: [safeeyes]

# When Safe Eyes is first installed it copies some initial configuration from
# /usr/lib/python3/dist-packages/safeeyes/config/ to ~/.config/safeeyes. We could do this
# manually but then it would break if Safe Eyes changes its behaviour. Note that this
# doesn't seem to properly start Safe Eyes so there's no need to kill it, but it does
# create the configuration.
- name: Start Safe Eyes to create initial configuration
  shell: safeeyes; sleep 1
  when: not result.stat.exists
  tags: [safeeyes]

# When Safe Eyes is first launched, it creates a symlink at ~/.config/autostart/safeeyes.desktop
# which we need to delete first to create our own autostart file
- name: Delete ~/.config/autostart/safeeyes.desktop symlink
  file:
    path: ~/.config/autostart/safeeyes.desktop
    state: absent
  when: not result.stat.exists
  tags: [safeeyes]

- name: Copy Safe Eyes configuration
  copy:
    src: safeeyes.json
    dest: ~/.config/safeeyes/safeeyes.json
  tags: [safeeyes]

- name: Configure Safe Eyes to autostart
  copy:
    src: /usr/share/applications/safeeyes.desktop
    dest: ~/.config/autostart/safeeyes.desktop
    # Don't overwrite the file since we'll modify it in the next step
    force: no
  tags: [safeeyes]

- name: Only autostart Safe Eyes on weekdays between 8:00 - 17:00
  replace:
    path: ~/.config/autostart/safeeyes.desktop
    regexp: '^Exec=.*'
    replace: "Exec=bash -c 'h=$(date +%%-H); [[ $(date +%%u) -le 5 && $h -ge 8 && $h -lt 17 ]] && env GDK_BACKEND=x11 safeeyes'"
  tags: [safeeyes]
