---
- name: Check if Docker CE is installed
  shell: dpkg -l docker-ce
  changed_when: no
  check_mode: no
  failed_when: no
  register: result
  tags: [docker, docker-install]

- name: Include Docker install tasks
  # Use dynamic include so skipped tasks won't show in output
  include_tasks: install.yml
  when: result.rc is defined and result.rc != 0
  tags: [docker, docker-install]

# This allows running docker commands without sudo
- name: Add user to docker group
  user:
    name: "{{ ansible_user_id }}"
    groups: docker
    append: yes
  become: yes

- name: Install Docker Compose
  get_url:
    url: https://github.com/docker/compose/releases/download/1.21.2/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: 0755
  become: yes
