---
- name: Check if Docker CE is installed
  shell: dpkg -l docker-ce
  changed_when: no
  check_mode: no
  failed_when: no
  register: result
  tags: [docker, docker-install]

- name: Include Docker install tasks
  # Use dynamic include so skipped tasks won't show in output
  include_tasks: install.yml
  when: result.rc is defined and result.rc != 0
  tags: [docker, docker-install]
