---
- import_tasks: clamav.yml
  tags: [office-desktop]

- name: Install desired packages
  apt:
    name:
      - fail2ban
      - ldap-utils
    state: present
  become: yes
  tags: [office-desktop]

- name: Configure fail2ban
  copy:
    src: jail.local
    dest: /etc/fail2ban/jail.local
    mode: 0444
  become: yes
  notify: Restart fail2ban
  tags: [office-desktop]

- name: Configure cups server
  lineinfile:
    path: /etc/cups/cups-browsed.conf
    line: BrowsePoll {{ cups_server }}
  become: yes
  notify: Restart cups-browsed
  tags: [office-desktop]

- name: Configure cups user
  lineinfile:
    path: ~/.profile
    line: export CUPS_USER={{ cups_user }}
  tags: [office-desktop]

- name: Add firewall rules
  ufw:
    rule: '{{ item.rule }}'
    port: '{{ item.port }}'
    proto: '{{ item.proto }}'
    src: '{{ item.src }}'
  loop: '{{ firewall_add }}'
  become: yes
  tags: [office-desktop]

- name: Delete firewall rules
  ufw:
    rule: '{{ item.rule }}'
    port: '{{ item.port }}'
    proto: '{{ item.proto }}'
    src: '{{ item.src }}'
    delete: yes
  loop: '{{ firewall_delete }}'
  become: yes
  tags: [office-desktop]

- name: Set default audio output device
  lineinfile:
    path: /etc/pulse/default.pa
    line: set-default-sink 0
  become: yes
  notify: Remove ~/.config/pulse
  tags: [office-desktop]

# This actually needs to be set from within the application (3 dots menu > Settings > Auto-start application) but we'll
# leave it here as a reminder
- name: Automatically start Teams on login
  copy:
    src: /usr/share/applications/teams.desktop
    dest: ~/.config/autostart/teams.desktop
    # Don't overwrite the file; the one Teams copies via the UI may be different
    force: no
  when:
    - "'teams' in ansible_role_names"
  tags: [office-desktop]

- name: Get the power manager plugin ID
  shell: xfconf-query -lv -c xfce4-panel | grep power-manager-plugin | awk '{print $1}'
  register: power_manager_plugin_id
  changed_when: no
  check_mode: no
  when:
    - "'ubuntu-xfce' in ansible_role_names"
  tags: [office-desktop]

- name: Remove the power manager plugin
  # This removes the plugin from xfconf, but not the list of active plugins
  shell: 'xfconf-query -c xfce4-panel -p {{ power_manager_plugin_id.stdout }} -r'
  # Restarting the panel will also remove the plugin from the list of active plugins
  notify: Restart Xfce panel
  when:
    - "'ubuntu-xfce' in ansible_role_names"
    - power_manager_plugin_id.stdout is defined and power_manager_plugin_id.stdout != ""
  tags: [office-desktop]
